# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true
# Permalinks
permalink:        pretty

# Server
source:           .
destination:      _site
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              https://docs.apnscp.com
encoding:         UTF-8
exclude:          [assets/scss/, Gemfile*]
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title: apnscp
description: A customizable, multi-user panel for the modern age.
twitter: apisnetworks
authors: Matt Saladna and contributors
social_logo_path: /images/apnscp-social.png
social_image_path: /images/apnscp-social.png

# Custom vars
current_version:  3.0-alpha
repo:             https://gitlab.com/apisnetworks/apnscp
slack:            none
reddit:           /r/apnscp
bootstrap_url: https://raw.githubusercontent.com/apisnetworks/apnscp-bootstrapper/master/bootstrap.sh
bootstrap_sha2: 47ea59a193c1953e5364a498f55daba7cdebf0a6d07ac2efc17c2521a1caf11a
tether_url: https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js
forums:           https://forums.apnscp.com
license:          https://my.apnscp.com

download:
  source:
  dist:
blog:             https://hq.apnscp.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css
  css_hash:       "sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js
  js_hash:        "sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
  jquery:         https://code.jquery.com/jquery-3.1.1.slim.min.js
  jquery_hash:    "sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
  tether:         https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js
  tether_hash:    "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
